---
- name: setup devtop
  hosts: all
  become: yes

  tasks:

  - apt_repository:
      repo: "{{ item }}"
      state: present
    with_items:
      - ppa:git-core/ppa

  - name: apt items setup
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
      
    with_items:
      - terminator
      - net-tools
      - curl
      - git
      - jq
      - ca-certificates
      - software-properties-common

  - name: install sublime 3 with commandline
    shell: |
      wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
      echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
      sudo apt update
      sudo apt install sublime-text

