---
- name: setup devtop
  hosts: all
  become: yes

  vars_files:
    - ./vars/user_vars.yml


  roles:
    - geerlingguy.docker
    - gantsign.maven

  tasks:

  - apt_repository:
      repo: "{{ item }}"
      state: present
    with_items:
      - ppa:git-core/ppa

  - name: apt items setup
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
      
    with_items:
      - terminator
      - net-tools
      - curl
      - git
      - jq
      - ca-certificates
      - software-properties-common
      - openjdk-8-jdk



  - name: install sublime 3 with commandline
    shell: |
      wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
      echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
      wget -O - https://dbeaver.io/debs/dbeaver.gpg.key | sudo apt-key add -
      echo "deb https://dbeaver.io/debs/dbeaver-ce /" | sudo tee /etc/apt/sources.list.d/dbeaver.list
      sudo apt update
      sudo apt install -y sublime-text
      sudo apt install -y dbeaver-ce

  - name: Install snap items with option --classic
    snap:
      name: "{{ item }}"
      classic: yes
      channel: edge

    with_items:
      - intellij-idea-community

  - name: Set env variables in .bashrc
    lineinfile:
      path: "{{ user_home }}/.bashrc"
      line: export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
      insertafter: EOF

