---
- name: setup devtop
  hosts: all
  become: yes

  vars:
   local_home: "{{ lookup('env','HOME') }}"


  roles:
    - geerlingguy.docker
    - gantsign.maven

  tasks:
  
  - name: Set timezone to Europe/Amsterdam
    timezone:
      name: Europe/Amsterdam

  - include: apt-custom.yml url="https://download.sublimetext.com/sublimehq-pub.gpg" repo_details="deb https://download.sublimetext.com/ apt/stable/" custom_file_name="sublime-text"
  - include: apt-custom.yml url="https://dbeaver.io/debs/dbeaver.gpg.key" repo_details="deb https://dbeaver.io/debs/dbeaver-ce /" custom_file_name="dbeaver"
  - include: apt-repo.yml repo_details="ppa:git-core/ppa" custom_file_name="git"

  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes
      upgrade: yes

  - name: apt items setup
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
      
    with_items:
      - terminator
      - net-tools
      - curl
      - git
      - jq
      - ca-certificates
      - software-properties-common
      - openjdk-8-jdk
      - sublime-text
      - dbeaver-ce
      - ppa-purge

  - include: cleanup.yml


  - name: Install snap items with option --classic
    snap:
      name: "{{ item }}"
      classic: yes
      channel: edge

    with_items:
      - intellij-idea-community
      - postman

  - name: Set env variables in .bashrc
    lineinfile:
      path: "{{ local_home }}/.bashrc"
      line: export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
      insertafter: EOF
